module.exports = {
  und: 'Other',
  eng: 'English',
  ger: 'German',
  pol: 'Polish',
  // spa: 'Spanish',
  // rus: 'Russian',
  // swe: 'Swedish',
  // tur: 'Turkish',
  // ukr: 'Ukrainian',
  // cze: 'Czech',
  // tha: 'Thai',
  // est: 'Estonian',
  // fin: 'Finnish',
  // fre: 'French ?',
  // fra: 'French ?',
  // ita: 'Italian',
  // jpn: 'Japanese',
  // kor: 'Korean',
  // nor: 'Norwegian',
  // por: 'Portugese ?',
  // hun: 'Hungarian',
  // ind: 'Hindi',
  // per: 'Spanish ?',
  // slo: 'Slovene'
  'EN / PL': 'English or Polish',
  '?': 'Other'
};
