export const FIELD_RESET_VISIBILITY = 'FIELD_RESET_VISIBILITY';
export const FIELD_SET_VISIBILITY = 'FIELD_SET_VISIBILITY';
export const FIELD_TOGGLE_VISIBILITY = 'FIELD_TOGGLE_VISIBILITY';

export const FILTER_RESET_VISIBILITY = 'FILTER_RESET_VISIBILITY';
export const FILTER_SET_SORT = 'FILTER_SET_SORT';
export const FILTER_SET_VALUE = 'FILTER_SET_VALUE';
export const FILTER_SET_VISIBILITY = 'FILTER_SET_VISIBILITY';

export const ITEMS_SET = 'ITEMS_SET';
export const LOADING = 'LOADING';
export const SCHEMA_SET = 'SCHEMA_SET';
